# minima them configuration options
title: "Michael James: Things to do"
author: Michael James
# email: your-email@example.com
description: >-
  Software Engineer and Systems Architect.
  I've got things to do, and they sometimes end up here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mj_heilmann 
github_username:  mjheilmann
linkedin_username: mjheilmann

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# display settings
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
